/**
 * Eclipse: Second Dawn for the Galaxy - Ship Parts
 *
 * Ship parts unlocked by researching technologies.
 * Each part has stats that affect ship performance in combat and movement.
 *
 * Stats:
 * - Energy Production (+): Generated by sources
 * - Energy Cost (-): Consumed by drives, weapons, computers, shields
 * - Initiative: Speed in combat (higher acts first)
 * - Shields: Dice roll penalty for attackers
 * - Hull: Damage capacity
 * - Weapons: Attack dice and damage
 *
 * Based on Eclipse Second Dawn board game rules.
 */

import { type DieFace } from './parts';

export type BoardGameShipPart = {
  id: string;
  name: string;
  category: 'Source' | 'Drive' | 'Weapon' | 'Computer' | 'Shield' | 'Hull';

  // Energy stats
  energyProduction?: number; // Sources produce energy
  energyCost?: number; // Most parts consume energy

  // Combat/movement stats
  initiative?: number; // Added to ship's initiative
  shields?: number; // Defense value (subtracted from attacker rolls)
  hull?: number; // Extra hull points

  // Weapon stats
  dice?: number; // Number of dice to roll
  dieColor?: 'yellow' | 'orange' | 'red'; // Ion=yellow(1dmg), Plasma=orange(2dmg), Antimatter=red(4dmg)
  damage?: number; // Base damage per hit
  hitRolls?: number[]; // Which die faces hit (e.g., [5,6] means 5 or 6 hits)

  // Computer stats
  computer?: number; // Targeting bonus (lowers hit threshold)

  // Special notes
  description?: string;
};

/**
 * SOURCES (Energy Generators)
 */
export const SOURCES: BoardGameShipPart[] = [
  {
    id: 'nuclear_source',
    name: 'Nuclear Source',
    category: 'Source',
    energyProduction: 3,
    description: 'Starting source. Produces 3 energy.'
  },
  {
    id: 'fusion_source',
    name: 'Fusion Source',
    category: 'Source',
    energyProduction: 3,
    description: 'Basic source unlocked by Fusion Source tech. Produces 3 energy.'
  },
  {
    id: 'tachyon_source',
    name: 'Tachyon Source',
    category: 'Source',
    energyProduction: 4,
    description: 'Advanced source. Produces 4 energy.'
  },
  {
    id: 'zero_point_source',
    name: 'Zero-Point Source',
    category: 'Source',
    energyProduction: 5,
    description: 'Rare advanced source. Produces 5 energy.'
  },
];

/**
 * DRIVES (Initiative & Movement)
 */
export const DRIVES: BoardGameShipPart[] = [
  {
    id: 'ion_drive',
    name: 'Ion Drive',
    category: 'Drive',
    energyCost: 0,
    initiative: 1,
    description: 'Starting drive. +1 initiative, no energy cost.'
  },
  {
    id: 'fusion_drive',
    name: 'Fusion Drive',
    category: 'Drive',
    energyCost: 1,
    initiative: 2,
    description: '+2 initiative, costs 1 energy.'
  },
  {
    id: 'tachyon_drive',
    name: 'Tachyon Drive',
    category: 'Drive',
    energyCost: 2,
    initiative: 3,
    description: '+3 initiative, costs 2 energy.'
  },
  {
    id: 'transition_drive',
    name: 'Transition Drive',
    category: 'Drive',
    energyCost: 1,
    initiative: 3,
    description: 'Rare efficient drive. +3 initiative, costs only 1 energy.'
  },
];

/**
 * WEAPONS
 */
export const WEAPONS: BoardGameShipPart[] = [
  {
    id: 'ion_cannon',
    name: 'Ion Cannon',
    category: 'Weapon',
    energyCost: 1,
    dice: 1,
    dieColor: 'yellow',
    damage: 1,
    hitRolls: [6],
    description: 'Starting weapon. 1 yellow die (hits on 6), 1 damage. Costs 1 energy.'
  },
  {
    id: 'plasma_cannon',
    name: 'Plasma Cannon',
    category: 'Weapon',
    energyCost: 2,
    dice: 1,
    dieColor: 'orange',
    damage: 2,
    hitRolls: [5, 6],
    description: '1 orange die (hits on 5-6), 2 damage. Costs 2 energy.'
  },
  {
    id: 'plasma_missile',
    name: 'Plasma Missile',
    category: 'Weapon',
    energyCost: 3,
    dice: 2,
    dieColor: 'orange',
    damage: 2,
    hitRolls: [4, 5, 6],
    description: '2 orange dice (hit on 4-6), 2 damage each. Costs 3 energy.'
  },
  {
    id: 'antimatter_cannon',
    name: 'Antimatter Cannon',
    category: 'Weapon',
    energyCost: 4,
    dice: 1,
    dieColor: 'red',
    damage: 4,
    hitRolls: [5, 6],
    description: '1 red die (hits on 5-6), 4 damage. Costs 4 energy.'
  },
  {
    id: 'flux_missile',
    name: 'Flux Missile',
    category: 'Weapon',
    energyCost: 3,
    dice: 2,
    dieColor: 'orange',
    damage: 2,
    hitRolls: [5, 6],
    description: 'Rare. 2 orange dice (hit on 5-6), 2 damage each. Costs 3 energy.'
  },
  {
    id: 'soliton_cannon',
    name: 'Soliton Cannon',
    category: 'Weapon',
    energyCost: 3,
    dice: 1,
    dieColor: 'red',
    damage: 4,
    hitRolls: [6],
    description: 'Rare. 1 red die (hits on 6), 4 damage. Costs 3 energy (cheaper than Antimatter).'
  },
  {
    id: 'rift_cannon',
    name: 'Rift Cannon',
    category: 'Weapon',
    energyCost: 2,
    dice: 1,
    dieColor: 'orange',
    damage: 2,
    hitRolls: [4, 5, 6], // Rift cannons typically have better hit chances
    description: 'Rare rift weapon. 1 orange die (hits on 4-6), 2 damage. Costs 2 energy.'
  },
];

/**
 * SHIELDS
 */
export const SHIELDS: BoardGameShipPart[] = [
  {
    id: 'gauss_shield',
    name: 'Gauss Shield',
    category: 'Shield',
    energyCost: 1,
    shields: 1,
    description: '+1 shield (enemy needs to roll 1 higher to hit). Costs 1 energy.'
  },
  {
    id: 'phase_shield',
    name: 'Phase Shield',
    category: 'Shield',
    energyCost: 2,
    shields: 2,
    description: '+2 shields (enemy needs to roll 2 higher to hit). Costs 2 energy.'
  },
  {
    id: 'absorption_shield',
    name: 'Absorption Shield',
    category: 'Shield',
    energyCost: 0,
    shields: 1,
    energyProduction: 2,
    description: 'Rare. +1 shield AND produces 2 energy (net +2 energy). No cost.'
  },
  {
    id: 'conifold_field',
    name: 'Conifold Field',
    category: 'Shield',
    energyCost: 1,
    shields: 3,
    description: 'Rare powerful shield. +3 shields. Costs 1 energy.'
  },
];

/**
 * HULL
 */
export const HULL: BoardGameShipPart[] = [
  {
    id: 'improved_hull',
    name: 'Improved Hull',
    category: 'Hull',
    energyCost: 0,
    hull: 1,
    description: '+1 hull point. No energy cost.'
  },
  {
    id: 'sentient_hull',
    name: 'Sentient Hull',
    category: 'Hull',
    energyCost: 0,
    hull: 1,
    computer: 1,
    description: 'Rare. +1 hull AND +1 computer (targeting). No energy cost.'
  },
];

/**
 * COMPUTERS (Targeting)
 */
export const COMPUTERS: BoardGameShipPart[] = [
  {
    id: 'electron_computer',
    name: 'Electron Computer',
    category: 'Computer',
    energyCost: 0,
    initiative: 1,
    computer: 1,
    description: 'Starting computer. +1 initiative, +1 computer (targeting). No cost.'
  },
  {
    id: 'positron_computer',
    name: 'Positron Computer',
    category: 'Computer',
    energyCost: 1,
    initiative: 1,
    computer: 1,
    description: '+1 initiative, +1 computer. Costs 1 energy.'
  },
  {
    id: 'gluon_computer',
    name: 'Gluon Computer',
    category: 'Computer',
    energyCost: 2,
    initiative: 1,
    computer: 2,
    description: '+1 initiative, +2 computer (better targeting). Costs 2 energy.'
  },
];

/**
 * All ship parts combined
 */
export const ALL_SHIP_PARTS: BoardGameShipPart[] = [
  ...SOURCES,
  ...DRIVES,
  ...WEAPONS,
  ...SHIELDS,
  ...HULL,
  ...COMPUTERS,
];

/**
 * Helper to get parts by ID
 */
export function getShipPartById(id: string): BoardGameShipPart | undefined {
  return ALL_SHIP_PARTS.find(p => p.id === id);
}

/**
 * Helper to get all parts for a category
 */
export function getPartsByCategory(category: BoardGameShipPart['category']): BoardGameShipPart[] {
  return ALL_SHIP_PARTS.filter(p => p.category === category);
}

/**
 * Summary stats
 */
export const SHIP_PART_STATS = {
  total: ALL_SHIP_PARTS.length,
  byCategory: {
    Source: SOURCES.length,
    Drive: DRIVES.length,
    Weapon: WEAPONS.length,
    Shield: SHIELDS.length,
    Hull: HULL.length,
    Computer: COMPUTERS.length,
  },
} as const;

/**
 * Convert board game ship part to roguelike Part format (for compatibility)
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function convertToRoguelikePart(bgPart: BoardGameShipPart): any {
  const faces: DieFace[] = [];

  // Build dice faces for weapons
  if (bgPart.hitRolls && bgPart.damage) {
    for (let i = 1; i <= 6; i++) {
      if (bgPart.hitRolls.includes(i)) {
        faces.push({ roll: i, dmg: bgPart.damage });
      } else {
        faces.push({ roll: i });
      }
    }
  }

  return {
    id: bgPart.id,
    name: bgPart.name,
    cat: bgPart.category,
    tech_category: 'Grid', // TODO: Map correctly based on which tech unlocks it
    tier: 1, // TODO: Determine tier from tech cost
    cost: 0, // Parts aren't purchased in board game, they're unlocked

    // Map stats
    powerProd: bgPart.energyProduction || 0,
    powerCost: bgPart.energyCost || 0,
    init: bgPart.initiative || 0,
    shieldTier: bgPart.shields || 0,
    extraHull: bgPart.hull || 0,
    aim: bgPart.computer || 0,

    // Weapon stats
    dice: bgPart.dice || 0,
    dmgPerHit: bgPart.damage || 0,
    faces: faces.length > 0 ? faces : undefined,

    desc: bgPart.description,
  };
}
